name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Gradle
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    # Grant executable permission to the Gradle wrapper script
    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew
    
    # Build the project using the Gradle wrapper
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # Run the IntegrationTest with the main method
    - name: Run Integration Test
      run: ./gradlew run

